services:
  meetroom-api:
    build: .                        # Build image from local Dockerfile
    container_name: meetroom
    ports:
      - "8000:8000"                 # Host 8000 -> container 8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - sqlite_store:/app/data
    develop:
      watch:
      - action: sync+restart
        path: .
        target: /app
      - action: rebuild
        path: requirements.txt
    
volumes:
  sqlite_store: 