services:
  meetroom-api:
    build: .                        # Build image from local Dockerfile
    container_name: meetroom
    ports:
      - "8000:8000"                 # Host 8000 -> container 8000
    env_file:
      - .env
    volumes:
      - type: volume
        source: sqlite-store
        target: /app/data
    networks:
      - meetroom-net
    develop:
      watch:
      - action: sync+restart
        path: ./app
        target: /app/app
        ignore:
          - __pycache__/
          - *.pyc
      - action: rebuild
        path: requirements.txt
    
volumes:
  sqlite-store: 

networks:
  meetroom-net: